version: 1.0.{build}

install:
- git submodule update --init --recursive

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      _NATIVE_BUILD_ARGS: Release win-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      _NATIVE_BUILD_ARGS: Release win-x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      _NATIVE_BUILD_ARGS: Release --android-ndk C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17 --android-abi arm64-v8a
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      _NATIVE_BUILD_ARGS: Release --android-ndk C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17 --android-abi armeabi-v7a
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804

before_build:
- sh: ./ext/sync-shaderc.sh
- cmd: call .\ext\sync-shaderc.cmd

build_script:
- sh: ./ci-build.sh
- cmd: call .\build-native.cmd %_NATIVE_BUILD_ARGS%

artifacts:
- path: build/Release/libveldrid-spirv.so
  name: libveldrid-spirv.so
- path: build\win-x64\Release\libveldrid-spirv.dll
  name: libveldrid-spirv.win-x64.dll
- path: build\win-x86\Release\libveldrid-spirv.dll
  name: libveldrid-spirv.win-x86.dll
- path: build\android-arm64-v8a\Release\libveldrid-spirv.so
  name: libveldrid-spirv.android-arm64-v8a.so
- path: build\android-armeabi-v7a\Release\libveldrid-spirv.so
  name: libveldrid-spirv.android-armeabi-v7a.so

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Native Release ($(APPVEYOR_BUILD_WORKER_IMAGE))'
  provider: GitHub
  auth_token:
    secure: DEGIcombPNY+d9ZUR4321jSr5Y+i03DkeiLvfEhzJtOFmaZrXVdS8B14mJQyqw8c
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
