version: 1.0.{build}
image:
- Ubuntu
- Visual Studio 2017
install:
- git submodule update --init --recursive
build_script:
- sh: ./build-native.sh release
- cmd: call .\build-native.cmd Release
artifacts:
- path: build/Release/libveldrid-spirv.so
  name: libveldrid-spirv.so
- path: build\Release\libveldrid-spirv.dll
  name: libveldrid-spirv.dll

deploy:
  release: $(appveyor_repo_tag_name)
  description: 'Native Release ($(appveyor_build_worker_image))'
  provider: GitHub
  auth_token:
    secure: DEGIcombPNY+d9ZUR4321jSr5Y+i03DkeiLvfEhzJtOFmaZrXVdS8B14mJQyqw8c
  artifacts: 
    - build/Release/libveldrid-spirv.so
    - build\Release\libveldrid-spirv.dll
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
